export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN ?? "",
  publicAppUrl: process.env.TASKFLOW_PUBLIC_URL ?? "",
  emailTokenEncryptionKey: process.env.EMAIL_TOKEN_ENCRYPTION_KEY ?? "",
  googleOAuthClientId: process.env.GOOGLE_OAUTH_CLIENT_ID ?? "",
  googleOAuthClientSecret: process.env.GOOGLE_OAUTH_CLIENT_SECRET ?? "",
  microsoftOAuthClientId: process.env.MICROSOFT_OAUTH_CLIENT_ID ?? "",
  microsoftOAuthClientSecret: process.env.MICROSOFT_OAUTH_CLIENT_SECRET ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  timesheetCsvUrl: process.env.TIMESHEET_CSV_URL ?? "",
  timesheetEmployeeMatch: process.env.TIMESHEET_EMPLOYEE_MATCH ?? "Pháp",
  timesheetStateFile: process.env.TIMESHEET_STATE_FILE ?? "",
};
