import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart";
import { useLanguage } from "@/hooks/useLanguage";
import { trpc } from "@/lib/trpc";
import { AlarmClock, BriefcaseBusiness, CalendarDays, Clock3, FileSpreadsheet, Loader2, RefreshCw, ShieldCheck, TriangleAlert } from "lucide-react";
import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, XAxis, YAxis } from "recharts";
import { TimesheetDutySchedule } from "@/components/TimesheetDutySchedule";

const monthNamesVi = ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"];
const monthNamesEn = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

function formatNumber(value: number, locale: string) {
  return new Intl.NumberFormat(locale, { maximumFractionDigits: 2 }).format(value);
}

function Kpi({ icon: Icon, value, label, note }: { icon: typeof Clock3; value: string; label: string; note: string }) {
  return <article className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[0_10px_28px_rgb(75_59_45/0.055)]"><div className="flex items-start justify-between gap-4"><div><p className="mono-label text-[var(--ink-muted)]">{label}</p><p className="mt-3 font-display text-4xl tracking-[-0.05em] text-[var(--ink)]">{value}</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--terracotta-soft)] text-[var(--terracotta-dark)]"><Icon className="h-5 w-5" aria-hidden="true" /></span></div><p className="mt-3 text-xs text-[var(--ink-muted)]">{note}</p></article>;
}

export function TimesheetDashboard() {
  const { language } = useLanguage();
  const isEnglish = language === "en";
  const now = new Date();
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [year, setYear] = useState(now.getFullYear());
  const [employeeName, setEmployeeName] = useState("");
  const locale = isEnglish ? "en-US" : "vi-VN";
  const monthNames = isEnglish ? monthNamesEn : monthNamesVi;
  const chartConfig = { hours: { label: isEnglish ? "Work hours" : "Giờ làm", color: "var(--terracotta)" } } satisfies ChartConfig;
  const access = trpc.timesheet.access.useQuery(undefined, { refetchOnWindowFocus: false });
  const people = trpc.timesheet.people.useQuery(undefined, { enabled: access.data?.canView === true, refetchOnWindowFocus: false });
  useEffect(() => { if (!employeeName && people.data?.[0]?.name) setEmployeeName(people.data[0].name); }, [employeeName, people.data]);
  const stats = trpc.timesheet.stats.useQuery({ month, year, employeeName }, { enabled: Boolean(employeeName), refetchOnWindowFocus: false });
  const years = Array.from({ length: 7 }, (_, index) => now.getFullYear() + 1 - index);
  const sharedDutySchedule = <TimesheetDutySchedule />;

  if (access.isLoading || people.isLoading || (employeeName && stats.isLoading)) return <div className="mx-auto max-w-7xl enter-up">{sharedDutySchedule}<section className="mt-6 grid min-h-40 place-items-center rounded-[22px] border border-[var(--line)] bg-[var(--surface)]" role="status"><div className="flex items-center gap-2 text-sm text-[var(--ink-muted)]"><Loader2 className="h-5 w-5 animate-spin text-[var(--terracotta)]" />{isEnglish ? "Loading detailed timesheet data" : "Đang tải dữ liệu chấm công chi tiết"}</div></section></div>;
  if (!access.data?.canView) return <div className="mx-auto max-w-7xl enter-up">{sharedDutySchedule}<section className="mt-6 mx-auto max-w-3xl rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-8 text-center shadow-sm"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[var(--terracotta-soft)] text-[var(--terracotta-dark)]"><ShieldCheck className="h-5 w-5" /></span><h2 className="mt-4 font-display text-2xl">{isEnglish ? "Timesheet access required" : "Cần được cấp quyền xem chấm công"}</h2><p className="mt-2 text-sm leading-6 text-[var(--ink-muted)]">{isEnglish ? "Ask the Timesheet administrator to approve your signed-in account. Detailed shared Timesheet source data remains protected." : "Hãy yêu cầu quản trị viên Timesheet phê duyệt tài khoản bạn đang đăng nhập. Dữ liệu nguồn chấm công chi tiết vẫn được bảo vệ."}</p></section></div>;
  if (people.isError || stats.isError) { const error = people.error ?? stats.error; return <div className="mx-auto max-w-7xl enter-up">{sharedDutySchedule}<section className="mt-6 mx-auto max-w-3xl rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-8 text-center shadow-sm"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[var(--terracotta-soft)] text-[var(--terracotta-dark)]"><TriangleAlert className="h-5 w-5" /></span><h2 className="mt-4 font-display text-2xl">{isEnglish ? "Timesheet data is unavailable" : "Chưa tải được dữ liệu chấm công"}</h2><p className="mt-2 text-sm text-[var(--ink-muted)]">{error?.message}</p><button type="button" className="swiss-button mt-5" onClick={() => { void people.refetch(); void stats.refetch(); }}><RefreshCw className="h-4 w-4" /> {isEnglish ? "Retry" : "Thử lại"}</button></section></div>; }
  if (!people.data?.length) return <div className="mx-auto max-w-7xl enter-up">{sharedDutySchedule}<section className="mt-6 mx-auto max-w-3xl rounded-[22px] border border-dashed border-[var(--line-strong)] bg-[var(--surface-soft)] p-8 text-center"><p className="text-sm text-[var(--ink-muted)]">{isEnglish ? "No valid names were found in the Timesheet source." : "Không tìm thấy tên hợp lệ trong nguồn chấm công."}</p></section></div>;
  if (!employeeName || !stats.data) return <div className="mx-auto max-w-7xl enter-up">{sharedDutySchedule}<div className="grid h-48 place-items-center text-sm text-[var(--ink-muted)]">{isEnglish ? "Select a name to view the dashboard." : "Chọn tên để xem dashboard."}</div></div>;
  if (!stats.data) return null;

  const data = stats.data;
  const periodLabel = isEnglish ? `${monthNames[month - 1]} ${year}` : data.period.label;
  return <div className="mx-auto max-w-7xl enter-up">
    {sharedDutySchedule}
    <section className="overflow-hidden rounded-[24px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_18px_55px_rgb(75_59_45/0.08)]">
      <div className="grid lg:grid-cols-[1fr_auto]"><div className="relative overflow-hidden p-6 md:p-8"><div className="pointer-events-none absolute -right-12 -top-20 h-52 w-52 rounded-full bg-[var(--terracotta-soft)]" /><p className="mono-label relative text-[var(--sage)]">Google Sheets / Timesheet</p><h2 className="relative mt-2 font-display text-4xl tracking-[-0.045em] md:text-5xl">{isEnglish ? "Make each workday visible." : "Nhịp làm việc, nhìn rõ từng ngày."}</h2><p className="relative mt-4 max-w-2xl text-sm leading-6 text-[var(--ink-muted)]">{isEnglish ? "Choose a recorded name to review that person's timesheet. The source URL and raw CSV stay on the server." : "Chọn tên đã ghi nhận để xem chấm công của người đó. URL nguồn và CSV thô luôn ở phía máy chủ."}</p></div><div className="flex flex-wrap items-end gap-3 border-t border-[var(--line)] bg-[var(--surface-soft)] p-5 lg:border-l lg:border-t-0"><label><span className="mono-label mb-2 block text-[var(--ink-muted)]">{isEnglish ? "Name" : "Tên nhân sự"}</span><select className="swiss-input min-w-44 max-w-full" value={employeeName} onChange={event => setEmployeeName(event.target.value)}>{people.data.map(person => <option key={person.name} value={person.name}>{person.name}</option>)}</select></label><label><span className="mono-label mb-2 block text-[var(--ink-muted)]">{isEnglish ? "Month" : "Tháng"}</span><select className="swiss-input min-w-36" value={month} onChange={event => setMonth(Number(event.target.value))}>{monthNames.map((name, index) => <option key={name} value={index + 1}>{name}</option>)}</select></label><label><span className="mono-label mb-2 block text-[var(--ink-muted)]">{isEnglish ? "Year" : "Năm"}</span><select className="swiss-input min-w-28" value={year} onChange={event => setYear(Number(event.target.value))}>{years.map(value => <option key={value} value={value}>{value}</option>)}</select></label></div></div>
      <div className="flex flex-wrap items-center gap-3 border-t border-[var(--line)] bg-[var(--butter)] px-6 py-4 text-sm text-[var(--ink)]"><span className="grid h-8 w-8 place-items-center rounded-full bg-[var(--surface)]"><FileSpreadsheet className="h-4 w-4" /></span><div><p className="font-semibold">{isEnglish ? "Timesheet source loaded securely" : "Đã tải nguồn chấm công an toàn"}</p><p className="mt-0.5 text-xs opacity-75">{isEnglish ? "The URL and raw CSV are processed on the server only." : "URL nguồn và CSV thô chỉ được xử lý ở phía máy chủ."}</p></div></div>
    </section>

    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label={isEnglish ? `Overview ${periodLabel}` : `Tổng quan ${periodLabel}`}>
      <Kpi icon={CalendarDays} value={String(data.summary.workDays)} label={isEnglish ? "Work days" : "Ngày làm việc"} note={isEnglish ? "Days with recorded work" : "Số ngày có ghi nhận công việc"} />
      <Kpi icon={Clock3} value={`${formatNumber(data.summary.totalHours, locale)}h`} label={isEnglish ? "Total hours" : "Tổng giờ"} note={isEnglish ? "From recorded start and end times" : "Cộng theo giờ bắt đầu và kết thúc"} />
      <Kpi icon={AlarmClock} value={formatNumber(data.summary.workUnits, locale)} label={isEnglish ? "Work units" : "Ngày công"} note={isEnglish ? "Calculated at 8 hours per unit" : "Quy đổi theo 8 giờ / công"} />
      <Kpi icon={BriefcaseBusiness} value={String(data.summary.taskCount)} label={isEnglish ? "Tasks" : "Công việc"} note={isEnglish ? "Recorded task rows in this period" : "Số dòng công việc trong kỳ"} />
    </section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_0.75fr]">
      <figure className="overflow-hidden rounded-[22px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_13px_34px_rgb(75_59_45/0.055)]"><figcaption className="border-b border-[var(--line)] p-5"><p className="mono-label text-[var(--terracotta)]">01 / {isEnglish ? "By day" : "Theo ngày"}</p><h3 className="mt-1 font-display text-2xl tracking-[-0.035em]">{isEnglish ? `Hours in ${periodLabel}` : `Giờ làm trong ${periodLabel.toLowerCase()}`}</h3></figcaption>{data.byDay.length ? <ChartContainer config={chartConfig} className="h-[300px] w-full p-4"><BarChart accessibilityLayer data={data.byDay} margin={{ left: -18, right: 8, top: 12 }}><CartesianGrid vertical={false} /><XAxis dataKey="day" tickLine={false} axisLine={false} tickMargin={8} /><YAxis tickLine={false} axisLine={false} /><ChartTooltip cursor={false} content={<ChartTooltipContent labelFormatter={label => isEnglish ? `Day ${label}` : `Ngày ${label}`} />} /><Bar dataKey="hours" fill="var(--color-hours)" radius={[7, 7, 2, 2]} /></BarChart></ChartContainer> : <div className="grid h-[300px] place-items-center p-8 text-center text-sm text-[var(--ink-muted)]">{isEnglish ? "No data in the selected month." : "Không có dữ liệu trong tháng đã chọn."}</div>}</figure>
      <figure className="overflow-hidden rounded-[22px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_13px_34px_rgb(75_59_45/0.055)]"><figcaption className="border-b border-[var(--line)] p-5"><p className="mono-label text-[var(--sage)]">02 / {isEnglish ? "Year" : "Cả năm"}</p><h3 className="mt-1 font-display text-2xl tracking-[-0.035em]">{isEnglish ? `Hours trend ${year}` : `Xu hướng giờ làm ${year}`}</h3></figcaption><ChartContainer config={chartConfig} className="h-[300px] w-full p-4"><LineChart accessibilityLayer data={data.yearTrend} margin={{ left: -18, right: 8, top: 12 }}><CartesianGrid vertical={false} /><XAxis dataKey="month" tickFormatter={value => isEnglish ? `M${value}` : `T${value}`} tickLine={false} axisLine={false} tickMargin={8} /><YAxis tickLine={false} axisLine={false} /><ChartTooltip cursor={false} content={<ChartTooltipContent labelFormatter={label => isEnglish ? `Month ${label}` : `Tháng ${label}`} />} /><Line dataKey="hours" type="monotone" stroke="var(--color-hours)" strokeWidth={3} dot={{ r: 3, fill: "var(--color-hours)" }} /></LineChart></ChartContainer></figure>
    </section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[0.8fr_1.2fr]">
      <div className="overflow-hidden rounded-[22px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_13px_34px_rgb(75_59_45/0.055)]"><div className="flex items-center justify-between border-b border-[var(--line)] p-5"><div><p className="mono-label text-[var(--terracotta)]">03 / {isEnglish ? "Distribution" : "Phân bổ"}</p><h3 className="mt-1 font-display text-2xl">{isEnglish ? "By work library" : "Theo thư viện công việc"}</h3></div><FileSpreadsheet className="h-5 w-5 text-[var(--ink-muted)]" /></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">{isEnglish ? `Timesheet distribution by library in ${periodLabel}` : `Phân bổ chấm công theo thư viện trong ${periodLabel}`}</caption><thead className="bg-[var(--surface-soft)] text-[11px] uppercase tracking-wide text-[var(--ink-muted)]"><tr><th className="px-5 py-3 font-semibold">{isEnglish ? "Library" : "Thư viện"}</th><th className="px-4 py-3 text-right font-semibold">{isEnglish ? "Tasks" : "Việc"}</th><th className="px-5 py-3 text-right font-semibold">{isEnglish ? "Hours" : "Giờ"}</th></tr></thead><tbody>{data.byLibrary.length ? data.byLibrary.map(item => <tr key={item.name} className="border-t border-[var(--line)]"><td className="max-w-72 px-5 py-3 font-medium">{item.name}</td><td className="px-4 py-3 text-right text-[var(--ink-muted)]">{item.taskCount}</td><td className="px-5 py-3 text-right font-semibold text-[var(--terracotta-dark)]">{formatNumber(item.hours, locale)}h</td></tr>) : <tr><td colSpan={3} className="px-5 py-12 text-center text-[var(--ink-muted)]">{isEnglish ? "No data." : "Không có dữ liệu."}</td></tr>}</tbody></table></div></div>
      <div className="overflow-hidden rounded-[22px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_13px_34px_rgb(75_59_45/0.055)]"><div className="border-b border-[var(--line)] p-5"><p className="mono-label text-[var(--sage)]">04 / {isEnglish ? "Details" : "Chi tiết"}</p><h3 className="mt-1 font-display text-2xl">{isEnglish ? "Daily summary" : "Tổng hợp từng ngày"}</h3></div><div className="max-h-[460px] overflow-auto"><table className="w-full text-left text-sm"><caption className="sr-only">{isEnglish ? `Daily timesheet details in ${periodLabel}` : `Chi tiết chấm công theo ngày trong ${periodLabel}`}</caption><thead className="sticky top-0 bg-[var(--surface-soft)] text-[11px] uppercase tracking-wide text-[var(--ink-muted)]"><tr><th className="px-5 py-3 font-semibold">{isEnglish ? "Day" : "Ngày"}</th><th className="px-4 py-3 text-right font-semibold">{isEnglish ? "Tasks" : "Số việc"}</th><th className="px-5 py-3 text-right font-semibold">{isEnglish ? "Hours worked" : "Giờ làm"}</th></tr></thead><tbody>{data.byDay.length ? data.byDay.map(item => <tr key={item.date} className="border-t border-[var(--line)]"><td className="px-5 py-3 font-semibold">{item.date}</td><td className="px-4 py-3 text-right text-[var(--ink-muted)]">{item.taskCount}</td><td className="px-5 py-3 text-right font-semibold">{formatNumber(item.hours, locale)}h</td></tr>) : <tr><td colSpan={3} className="px-5 py-12 text-center text-[var(--ink-muted)]">{isEnglish ? "No data." : "Không có dữ liệu."}</td></tr>}</tbody><tfoot className="border-t border-[var(--line-strong)] bg-[var(--surface-soft)] font-semibold"><tr><td className="px-5 py-3">{isEnglish ? "Total" : "Tổng"}</td><td className="px-4 py-3 text-right">{data.summary.taskCount}</td><td className="px-5 py-3 text-right text-[var(--terracotta-dark)]">{formatNumber(data.summary.totalHours, locale)}h</td></tr></tfoot></table></div></div>
    </section>
    <p className="mt-4 px-2 text-xs text-[var(--ink-muted)]">{isEnglish ? "Updated from Google Sheets at" : "Cập nhật từ Google Sheets lúc"} {new Intl.DateTimeFormat(locale, { dateStyle: "short", timeStyle: "medium" }).format(new Date(data.source.fetchedAt))} · {data.source.rowCount} {isEnglish ? "matching rows for the selected name." : "dòng phù hợp với tên đã chọn."}</p>
  </div>;
}
