import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart";
import { trpc } from "@/lib/trpc";
import { AlarmClock, BriefcaseBusiness, CalendarDays, CheckCircle2, Clock3, FileSpreadsheet, Loader2, RefreshCw, Send, TriangleAlert } from "lucide-react";
import { useState } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, XAxis, YAxis } from "recharts";

const monthNames = ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"];
const chartConfig = { hours: { label: "Giờ làm", color: "var(--terracotta)" } } satisfies ChartConfig;

function formatNumber(value: number) {
  return new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 2 }).format(value);
}

function Kpi({ icon: Icon, value, label, note }: { icon: typeof Clock3; value: string; label: string; note: string }) {
  return <article className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[0_10px_28px_rgb(75_59_45/0.055)]"><div className="flex items-start justify-between gap-4"><div><p className="mono-label text-[var(--ink-muted)]">{label}</p><p className="mt-3 font-display text-4xl tracking-[-0.05em] text-[var(--ink)]">{value}</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--terracotta-soft)] text-[var(--terracotta-dark)]"><Icon className="h-5 w-5" aria-hidden="true" /></span></div><p className="mt-3 text-xs text-[var(--ink-muted)]">{note}</p></article>;
}

export function TimesheetDashboard() {
  const now = new Date();
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [year, setYear] = useState(now.getFullYear());
  const stats = trpc.timesheet.stats.useQuery({ month, year }, { refetchOnWindowFocus: false });
  const years = Array.from({ length: 7 }, (_, index) => now.getFullYear() + 1 - index);

  if (stats.isLoading) return <div className="grid h-80 place-items-center" role="status"><Loader2 className="h-6 w-6 animate-spin text-[var(--terracotta)]" /><span className="sr-only">Đang tải dữ liệu chấm công</span></div>;
  if (stats.isError) return <section className="mx-auto max-w-3xl rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-8 text-center shadow-sm"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[var(--terracotta-soft)] text-[var(--terracotta-dark)]"><TriangleAlert className="h-5 w-5" /></span><h2 className="mt-4 font-display text-2xl">Chưa tải được dữ liệu chấm công</h2><p className="mt-2 text-sm text-[var(--ink-muted)]">{stats.error.message}</p><button type="button" className="swiss-button mt-5" onClick={() => stats.refetch()}><RefreshCw className="h-4 w-4" /> Thử lại</button></section>;
  if (!stats.data) return null;

  const data = stats.data;
  const sentDate = data.report.sentAt ? new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(data.report.sentAt)) : null;
  return <div className="mx-auto max-w-7xl enter-up">
    <section className="overflow-hidden rounded-[24px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_18px_55px_rgb(75_59_45/0.08)]">
      <div className="grid lg:grid-cols-[1fr_auto]"><div className="relative overflow-hidden p-6 md:p-8"><div className="pointer-events-none absolute -right-12 -top-20 h-52 w-52 rounded-full bg-[var(--terracotta-soft)]" /><p className="mono-label relative text-[var(--sage)]">Google Sheets / Timesheet</p><h2 className="relative mt-2 font-display text-4xl tracking-[-0.045em] md:text-5xl">Nhịp làm việc, nhìn rõ từng ngày.</h2><p className="relative mt-4 max-w-2xl text-sm leading-6 text-[var(--ink-muted)]">Dữ liệu được tổng hợp trực tiếp từ bảng chấm công. Thông tin gửi báo cáo và SMTP chỉ được xử lý tại backend.</p></div><div className="flex flex-wrap items-center gap-3 border-t border-[var(--line)] bg-[var(--surface-soft)] p-5 lg:border-l lg:border-t-0"><label><span className="mono-label mb-2 block text-[var(--ink-muted)]">Tháng</span><select className="swiss-input min-w-36" value={month} onChange={event => setMonth(Number(event.target.value))}>{monthNames.map((name, index) => <option key={name} value={index + 1}>{name}</option>)}</select></label><label><span className="mono-label mb-2 block text-[var(--ink-muted)]">Năm</span><select className="swiss-input min-w-28" value={year} onChange={event => setYear(Number(event.target.value))}>{years.map(value => <option key={value} value={value}>{value}</option>)}</select></label></div></div>
      <div className={`flex flex-wrap items-center gap-3 border-t border-[var(--line)] px-6 py-4 text-sm ${data.report.sent ? "bg-[var(--sage-soft)] text-[var(--sage)]" : "bg-[var(--butter)] text-[var(--ink)]"}`}><span className="grid h-8 w-8 place-items-center rounded-full bg-[var(--surface)]">{data.report.sent ? <CheckCircle2 className="h-4 w-4" /> : <Send className="h-4 w-4" />}</span><div><p className="font-semibold">{data.report.sent ? "Báo cáo tháng này đã được gửi" : "Báo cáo tháng này chưa được ghi nhận đã gửi"}</p><p className="mt-0.5 text-xs opacity-75">{sentDate ? `Gửi lúc ${sentDate}` : "Trạng thái lấy từ nhật ký gửi báo cáo của backend."}</p></div></div>
    </section>

    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label={`Tổng quan ${data.period.label}`}>
      <Kpi icon={CalendarDays} value={String(data.summary.workDays)} label="Ngày làm việc" note="Số ngày có ghi nhận công việc" />
      <Kpi icon={Clock3} value={`${formatNumber(data.summary.totalHours)}h`} label="Tổng giờ" note="Cộng theo giờ bắt đầu và kết thúc" />
      <Kpi icon={AlarmClock} value={formatNumber(data.summary.workUnits)} label="Ngày công" note="Quy đổi theo 8 giờ / công" />
      <Kpi icon={BriefcaseBusiness} value={String(data.summary.taskCount)} label="Công việc" note="Số dòng công việc trong kỳ" />
    </section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_0.75fr]">
      <figure className="overflow-hidden rounded-[22px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_13px_34px_rgb(75_59_45/0.055)]"><figcaption className="border-b border-[var(--line)] p-5"><p className="mono-label text-[var(--terracotta)]">01 / Theo ngày</p><h3 className="mt-1 font-display text-2xl tracking-[-0.035em]">Giờ làm trong {data.period.label.toLowerCase()}</h3></figcaption>{data.byDay.length ? <ChartContainer config={chartConfig} className="h-[300px] w-full p-4"><BarChart accessibilityLayer data={data.byDay} margin={{ left: -18, right: 8, top: 12 }}><CartesianGrid vertical={false} /><XAxis dataKey="day" tickLine={false} axisLine={false} tickMargin={8} /><YAxis tickLine={false} axisLine={false} /><ChartTooltip cursor={false} content={<ChartTooltipContent labelFormatter={label => `Ngày ${label}`} />} /><Bar dataKey="hours" fill="var(--color-hours)" radius={[7, 7, 2, 2]} /></BarChart></ChartContainer> : <div className="grid h-[300px] place-items-center p-8 text-center text-sm text-[var(--ink-muted)]">Không có dữ liệu trong tháng đã chọn.</div>}</figure>
      <figure className="overflow-hidden rounded-[22px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_13px_34px_rgb(75_59_45/0.055)]"><figcaption className="border-b border-[var(--line)] p-5"><p className="mono-label text-[var(--sage)]">02 / Cả năm</p><h3 className="mt-1 font-display text-2xl tracking-[-0.035em]">Xu hướng giờ làm {year}</h3></figcaption><ChartContainer config={chartConfig} className="h-[300px] w-full p-4"><LineChart accessibilityLayer data={data.yearTrend} margin={{ left: -18, right: 8, top: 12 }}><CartesianGrid vertical={false} /><XAxis dataKey="month" tickFormatter={value => `T${value}`} tickLine={false} axisLine={false} tickMargin={8} /><YAxis tickLine={false} axisLine={false} /><ChartTooltip cursor={false} content={<ChartTooltipContent labelFormatter={label => `Tháng ${label}`} />} /><Line dataKey="hours" type="monotone" stroke="var(--color-hours)" strokeWidth={3} dot={{ r: 3, fill: "var(--color-hours)" }} /></LineChart></ChartContainer></figure>
    </section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[0.8fr_1.2fr]">
      <div className="overflow-hidden rounded-[22px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_13px_34px_rgb(75_59_45/0.055)]"><div className="flex items-center justify-between border-b border-[var(--line)] p-5"><div><p className="mono-label text-[var(--terracotta)]">03 / Phân bổ</p><h3 className="mt-1 font-display text-2xl">Theo thư viện công việc</h3></div><FileSpreadsheet className="h-5 w-5 text-[var(--ink-muted)]" /></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Phân bổ chấm công theo thư viện trong {data.period.label}</caption><thead className="bg-[var(--surface-soft)] text-[11px] uppercase tracking-wide text-[var(--ink-muted)]"><tr><th className="px-5 py-3 font-semibold">Thư viện</th><th className="px-4 py-3 text-right font-semibold">Việc</th><th className="px-5 py-3 text-right font-semibold">Giờ</th></tr></thead><tbody>{data.byLibrary.length ? data.byLibrary.map(item => <tr key={item.name} className="border-t border-[var(--line)]"><td className="max-w-72 px-5 py-3 font-medium">{item.name}</td><td className="px-4 py-3 text-right text-[var(--ink-muted)]">{item.taskCount}</td><td className="px-5 py-3 text-right font-semibold text-[var(--terracotta-dark)]">{formatNumber(item.hours)}h</td></tr>) : <tr><td colSpan={3} className="px-5 py-12 text-center text-[var(--ink-muted)]">Không có dữ liệu.</td></tr>}</tbody></table></div></div>
      <div className="overflow-hidden rounded-[22px] border border-[var(--line)] bg-[var(--surface)] shadow-[0_13px_34px_rgb(75_59_45/0.055)]"><div className="border-b border-[var(--line)] p-5"><p className="mono-label text-[var(--sage)]">04 / Chi tiết</p><h3 className="mt-1 font-display text-2xl">Tổng hợp từng ngày</h3></div><div className="max-h-[460px] overflow-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Chi tiết chấm công theo ngày trong {data.period.label}</caption><thead className="sticky top-0 bg-[var(--surface-soft)] text-[11px] uppercase tracking-wide text-[var(--ink-muted)]"><tr><th className="px-5 py-3 font-semibold">Ngày</th><th className="px-4 py-3 text-right font-semibold">Số việc</th><th className="px-5 py-3 text-right font-semibold">Giờ làm</th></tr></thead><tbody>{data.byDay.length ? data.byDay.map(item => <tr key={item.date} className="border-t border-[var(--line)]"><td className="px-5 py-3 font-semibold">{item.date}</td><td className="px-4 py-3 text-right text-[var(--ink-muted)]">{item.taskCount}</td><td className="px-5 py-3 text-right font-semibold">{formatNumber(item.hours)}h</td></tr>) : <tr><td colSpan={3} className="px-5 py-12 text-center text-[var(--ink-muted)]">Không có dữ liệu.</td></tr>}</tbody><tfoot className="border-t border-[var(--line-strong)] bg-[var(--surface-soft)] font-semibold"><tr><td className="px-5 py-3">Tổng</td><td className="px-4 py-3 text-right">{data.summary.taskCount}</td><td className="px-5 py-3 text-right text-[var(--terracotta-dark)]">{formatNumber(data.summary.totalHours)}h</td></tr></tfoot></table></div></div>
    </section>
    <p className="mt-4 px-2 text-xs text-[var(--ink-muted)]">Cập nhật từ Google Sheets lúc {new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "medium" }).format(new Date(data.source.fetchedAt))} · {data.source.rowCount} dòng của nhân sự phù hợp.</p>
  </div>;
}
